// Generated by scripts/generate-db-migrations.mjs. Do not edit.
export const DATABASE_MIGRATIONS = Object.freeze([
  {
    "version": 1,
    "name": "initial_projects",
    "checksum": "35c5016e7ae358e1a8f477845b742f6738661a43959baf78dfc8d3d98deabc18",
    "destructive": false,
    "requiresProjectExport": false,
    "statements": [
      "CREATE TABLE projects (\n  id TEXT PRIMARY KEY,\n  name TEXT NOT NULL,\n  active_plan_id TEXT NOT NULL,\n  created_at TEXT NOT NULL,\n  updated_at TEXT NOT NULL\n)",
      "CREATE TABLE project_states (\n  project_id TEXT PRIMARY KEY REFERENCES projects(id) ON DELETE CASCADE,\n  schema_version INTEGER NOT NULL,\n  snapshot_json TEXT NOT NULL,\n  updated_at TEXT NOT NULL\n)",
      "CREATE INDEX idx_projects_updated_at ON projects(updated_at DESC)"
    ]
  },
  {
    "version": 2,
    "name": "project_lifecycle",
    "checksum": "60b091a88ba6bfd1c5a327d7ba594e6c9d74e72579696e0057804bc9636e7f4b",
    "destructive": false,
    "requiresProjectExport": false,
    "statements": [
      "ALTER TABLE projects ADD COLUMN provenance_json TEXT",
      "ALTER TABLE projects ADD COLUMN archived_at TEXT",
      "ALTER TABLE projects ADD COLUMN deleted_at TEXT",
      "ALTER TABLE projects ADD COLUMN recovery_until TEXT",
      "ALTER TABLE projects ADD COLUMN pinned INTEGER NOT NULL DEFAULT 0",
      "ALTER TABLE projects ADD COLUMN last_opened_at TEXT"
    ]
  },
  {
    "version": 3,
    "name": "accounts_and_tenancy",
    "checksum": "9818dbe0d6e276af37e70d245f7c9558b1ad803458786ebef315e9af4ed10836",
    "destructive": false,
    "requiresProjectExport": false,
    "statements": [
      "CREATE TABLE users (\n  id TEXT PRIMARY KEY,\n  identity_provider TEXT NOT NULL,\n  provider_subject TEXT NOT NULL,\n  email TEXT NOT NULL,\n  display_name TEXT,\n  status TEXT NOT NULL DEFAULT 'active',\n  created_at TEXT NOT NULL,\n  updated_at TEXT NOT NULL,\n  deleted_at TEXT,\n  UNIQUE(identity_provider, provider_subject)\n)",
      "CREATE TABLE organizations (\n  id TEXT PRIMARY KEY,\n  name TEXT NOT NULL,\n  slug TEXT NOT NULL UNIQUE,\n  created_by TEXT NOT NULL REFERENCES users(id),\n  created_at TEXT NOT NULL,\n  updated_at TEXT NOT NULL,\n  deleted_at TEXT\n)",
      "CREATE TABLE organization_memberships (\n  organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,\n  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  roles_json TEXT NOT NULL,\n  status TEXT NOT NULL DEFAULT 'active',\n  created_at TEXT NOT NULL,\n  updated_at TEXT NOT NULL,\n  PRIMARY KEY (organization_id, user_id)\n)",
      "CREATE TABLE organization_invitations (\n  id TEXT PRIMARY KEY,\n  organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,\n  email TEXT NOT NULL,\n  roles_json TEXT NOT NULL,\n  token_hash TEXT NOT NULL UNIQUE,\n  invited_by TEXT NOT NULL REFERENCES users(id),\n  created_at TEXT NOT NULL,\n  expires_at TEXT NOT NULL,\n  accepted_at TEXT,\n  revoked_at TEXT\n)",
      "CREATE TABLE user_sessions (\n  id TEXT PRIMARY KEY,\n  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  created_at TEXT NOT NULL,\n  expires_at TEXT NOT NULL,\n  revoked_at TEXT,\n  last_seen_at TEXT NOT NULL\n)",
      "CREATE TABLE organization_audit_events (\n  id TEXT PRIMARY KEY,\n  organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,\n  event_type TEXT NOT NULL,\n  actor_user_id TEXT NOT NULL,\n  target_user_id TEXT,\n  details_json TEXT NOT NULL,\n  fingerprint TEXT NOT NULL,\n  occurred_at TEXT NOT NULL\n)",
      "CREATE TABLE account_deletion_requests (\n  id TEXT PRIMARY KEY,\n  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  requested_at TEXT NOT NULL,\n  completed_at TEXT,\n  status TEXT NOT NULL\n)",
      "ALTER TABLE projects ADD COLUMN organization_id TEXT REFERENCES organizations(id)",
      "INSERT INTO users (id, identity_provider, provider_subject, email, display_name, status, created_at, updated_at)\nSELECT 'user-legacy-migration', 'migration', 'legacy-project-owner', 'legacy-projects@venuemind.invalid', 'LEGACY', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP\nWHERE EXISTS (SELECT 1 FROM projects) AND NOT EXISTS (SELECT 1 FROM users WHERE id = 'user-legacy-migration')",
      "INSERT INTO organizations (id, name, slug, created_by, created_at, updated_at)\nSELECT 'org-legacy-migration', 'LEGACY', 'legacy-migration', 'user-legacy-migration', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP\nWHERE EXISTS (SELECT 1 FROM projects) AND NOT EXISTS (SELECT 1 FROM organizations WHERE id = 'org-legacy-migration')",
      "INSERT INTO organization_memberships (organization_id, user_id, roles_json, status, created_at, updated_at)\nSELECT 'org-legacy-migration', 'user-legacy-migration', '[\"organization-administrator\"]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP\nWHERE EXISTS (SELECT 1 FROM projects) AND NOT EXISTS (SELECT 1 FROM organization_memberships WHERE organization_id = 'org-legacy-migration' AND user_id = 'user-legacy-migration')",
      "UPDATE projects SET organization_id = 'org-legacy-migration' WHERE organization_id IS NULL",
      "CREATE INDEX idx_projects_organization_updated ON projects(organization_id, updated_at DESC)",
      "CREATE INDEX idx_memberships_user ON organization_memberships(user_id, status)",
      "CREATE INDEX idx_invitations_organization_email ON organization_invitations(organization_id, email)",
      "CREATE INDEX idx_sessions_user ON user_sessions(user_id, expires_at)",
      "CREATE INDEX idx_account_audit_organization ON organization_audit_events(organization_id, occurred_at DESC)"
    ]
  },
  {
    "version": 4,
    "name": "optimistic_concurrency",
    "checksum": "bfac1ab0c7d6320045da6af0863e094ff270087262d56fa8507ab414a59b169b",
    "destructive": false,
    "requiresProjectExport": false,
    "statements": [
      "ALTER TABLE projects ADD COLUMN revision INTEGER NOT NULL DEFAULT 1",
      "ALTER TABLE projects ADD COLUMN write_token TEXT",
      "CREATE UNIQUE INDEX idx_projects_write_token ON projects(write_token) WHERE write_token IS NOT NULL"
    ]
  },
  {
    "version": 5,
    "name": "realtime_collaboration",
    "checksum": "9aaa50b1ee0f730ede2ba825a035471c2559cbd6dcb87524139822648478bea8",
    "destructive": false,
    "requiresProjectExport": false,
    "statements": [
      "CREATE TABLE project_collaboration_events (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,\n  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n  previous_event_id INTEGER,\n  event_type TEXT NOT NULL,\n  actor_user_id TEXT NOT NULL REFERENCES users(id),\n  session_id TEXT NOT NULL,\n  project_revision INTEGER NOT NULL,\n  payload_json TEXT NOT NULL,\n  occurred_at TEXT NOT NULL\n)",
      "CREATE INDEX idx_collaboration_events_project_cursor ON project_collaboration_events(organization_id, project_id, id)",
      "CREATE TABLE project_presence (\n  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n  organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,\n  session_id TEXT NOT NULL,\n  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  display_name TEXT NOT NULL,\n  plan_version TEXT NOT NULL,\n  focused_object_id TEXT,\n  viewport_json TEXT,\n  last_seen_at TEXT NOT NULL,\n  expires_at TEXT NOT NULL,\n  PRIMARY KEY (project_id, session_id)\n)",
      "CREATE INDEX idx_project_presence_expiry ON project_presence(organization_id, project_id, expires_at)"
    ]
  },
  {
    "version": 6,
    "name": "sharing_notifications",
    "checksum": "b7271cddc304567f93e12c4177069a91187a2ab92a6ded865d5e625b8c05034d",
    "destructive": false,
    "requiresProjectExport": false,
    "statements": [
      "CREATE TABLE project_share_links (\n  id TEXT PRIMARY KEY,\n  organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,\n  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n  proposal_id TEXT,\n  scope TEXT NOT NULL CHECK (scope IN ('read-only', 'reviewer')),\n  token_hash TEXT NOT NULL UNIQUE,\n  created_by TEXT NOT NULL REFERENCES users(id),\n  created_at TEXT NOT NULL,\n  expires_at TEXT NOT NULL,\n  revoked_at TEXT,\n  revoked_by TEXT REFERENCES users(id)\n)",
      "CREATE INDEX idx_share_links_project ON project_share_links(organization_id, project_id, created_at DESC)",
      "CREATE TABLE notification_preferences (\n  user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,\n  in_app_enabled INTEGER NOT NULL DEFAULT 1,\n  email_enabled INTEGER NOT NULL DEFAULT 0,\n  event_types_json TEXT NOT NULL DEFAULT '[\"review_requested\",\"adjustment_requested\",\"approval_completed\",\"conflict_detected\"]',\n  updated_at TEXT NOT NULL\n)",
      "CREATE TABLE notifications (\n  id TEXT PRIMARY KEY,\n  organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,\n  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  event_type TEXT NOT NULL,\n  body_code TEXT NOT NULL,\n  subject_refs_json TEXT NOT NULL,\n  created_at TEXT NOT NULL,\n  read_at TEXT\n)",
      "CREATE INDEX idx_notifications_user_unread ON notifications(user_id, read_at, created_at DESC)",
      "CREATE TABLE notification_email_outbox (\n  id TEXT PRIMARY KEY,\n  notification_id TEXT NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,\n  recipient_email TEXT NOT NULL,\n  body_code TEXT NOT NULL,\n  subject_refs_json TEXT NOT NULL,\n  created_at TEXT NOT NULL,\n  delivered_at TEXT,\n  failure_code TEXT\n)"
    ]
  },
  {
    "version": 7,
    "name": "sharing_delivery_integrity",
    "checksum": "acab21ce5eb3565a9f9b322371a7bbd1d9efc09acac124f91a8c0cac0d438d1e",
    "destructive": false,
    "requiresProjectExport": false,
    "statements": [
      "CREATE UNIQUE INDEX idx_projects_id_organization ON projects(id, organization_id)",
      "ALTER TABLE project_share_links ADD COLUMN lifecycle_state TEXT NOT NULL DEFAULT 'active' CHECK (lifecycle_state IN ('pending-create', 'active', 'pending-revoke', 'revoked'))",
      "ALTER TABLE project_share_links ADD COLUMN creation_ledgered_at TEXT",
      "ALTER TABLE project_share_links ADD COLUMN revocation_ledgered_at TEXT",
      "ALTER TABLE project_share_links ADD COLUMN operation_attempts INTEGER NOT NULL DEFAULT 0",
      "ALTER TABLE project_share_links ADD COLUMN last_operation_error TEXT",
      "UPDATE project_share_links SET creation_ledgered_at = created_at WHERE lifecycle_state = 'active' AND creation_ledgered_at IS NULL",
      "UPDATE project_share_links SET lifecycle_state = 'pending-revoke' WHERE revoked_at IS NOT NULL",
      "ALTER TABLE notifications ADD COLUMN in_app_visible INTEGER NOT NULL DEFAULT 1 CHECK (in_app_visible IN (0, 1))",
      "ALTER TABLE notification_email_outbox ADD COLUMN attempt_count INTEGER NOT NULL DEFAULT 0",
      "ALTER TABLE notification_email_outbox ADD COLUMN last_attempt_at TEXT",
      "ALTER TABLE notification_email_outbox ADD COLUMN lease_token TEXT",
      "ALTER TABLE notification_email_outbox ADD COLUMN lease_expires_at TEXT",
      "CREATE INDEX idx_share_links_pending ON project_share_links(lifecycle_state, created_at)",
      "CREATE INDEX idx_email_outbox_pending ON notification_email_outbox(delivered_at, lease_expires_at, created_at)",
      "CREATE TRIGGER validate_share_link_insert BEFORE INSERT ON project_share_links BEGIN\n  SELECT CASE WHEN length(NEW.token_hash) != 64 OR NEW.token_hash GLOB '*[^0-9a-f]*' THEN RAISE(ABORT, 'SHARE_LINK_TOKEN_INVALID') END;\n  SELECT CASE WHEN NOT ((NEW.scope = 'read-only' AND NEW.proposal_id IS NULL) OR (NEW.scope = 'reviewer' AND NEW.proposal_id IS NOT NULL AND length(NEW.proposal_id) > 0)) THEN RAISE(ABORT, 'SHARE_LINK_SCOPE_INVALID') END;\n  SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM projects p WHERE p.id = NEW.project_id AND p.organization_id = NEW.organization_id) THEN RAISE(ABORT, 'SHARE_LINK_ORGANIZATION_INVALID') END;\n  SELECT CASE WHEN NEW.expires_at <= NEW.created_at THEN RAISE(ABORT, 'SHARE_LINK_EXPIRY_INVALID') END;\nEND",
      "CREATE TRIGGER validate_share_link_update BEFORE UPDATE ON project_share_links BEGIN\n  SELECT CASE WHEN length(NEW.token_hash) != 64 OR NEW.token_hash GLOB '*[^0-9a-f]*' THEN RAISE(ABORT, 'SHARE_LINK_TOKEN_INVALID') END;\n  SELECT CASE WHEN NOT ((NEW.scope = 'read-only' AND NEW.proposal_id IS NULL) OR (NEW.scope = 'reviewer' AND NEW.proposal_id IS NOT NULL AND length(NEW.proposal_id) > 0)) THEN RAISE(ABORT, 'SHARE_LINK_SCOPE_INVALID') END;\n  SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM projects p WHERE p.id = NEW.project_id AND p.organization_id = NEW.organization_id) THEN RAISE(ABORT, 'SHARE_LINK_ORGANIZATION_INVALID') END;\n  SELECT CASE WHEN NEW.expires_at <= NEW.created_at THEN RAISE(ABORT, 'SHARE_LINK_EXPIRY_INVALID') END;\n  SELECT CASE WHEN NOT ((NEW.revoked_at IS NULL AND NEW.revoked_by IS NULL) OR (NEW.revoked_at IS NOT NULL AND NEW.revoked_by IS NOT NULL)) THEN RAISE(ABORT, 'SHARE_LINK_REVOCATION_INVALID') END;\n  SELECT CASE WHEN NEW.lifecycle_state IN ('pending-revoke', 'revoked') AND NEW.revoked_at IS NULL THEN RAISE(ABORT, 'SHARE_LINK_REVOCATION_INVALID') END;\n  SELECT CASE WHEN NEW.lifecycle_state = 'active' AND NEW.creation_ledgered_at IS NULL THEN RAISE(ABORT, 'SHARE_LINK_LEDGER_INVALID') END;\n  SELECT CASE WHEN NEW.lifecycle_state = 'revoked' AND NEW.revocation_ledgered_at IS NULL THEN RAISE(ABORT, 'SHARE_LINK_LEDGER_INVALID') END;\nEND",
      "CREATE TRIGGER validate_notification_insert BEFORE INSERT ON notifications BEGIN\n  SELECT CASE WHEN NEW.event_type NOT IN ('review_requested', 'adjustment_requested', 'approval_completed', 'conflict_detected') OR NEW.body_code != ('notification.' || NEW.event_type) THEN RAISE(ABORT, 'NOTIFICATION_TYPE_INVALID') END;\n  SELECT CASE WHEN NOT json_valid(NEW.subject_refs_json) OR json_type(NEW.subject_refs_json) != 'object' THEN RAISE(ABORT, 'NOTIFICATION_REFS_INVALID') END;\n  SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM projects p WHERE p.id = NEW.project_id AND p.organization_id = NEW.organization_id) THEN RAISE(ABORT, 'NOTIFICATION_ORGANIZATION_INVALID') END;\nEND",
      "CREATE TRIGGER validate_notification_update BEFORE UPDATE ON notifications BEGIN\n  SELECT CASE WHEN NEW.event_type NOT IN ('review_requested', 'adjustment_requested', 'approval_completed', 'conflict_detected') OR NEW.body_code != ('notification.' || NEW.event_type) THEN RAISE(ABORT, 'NOTIFICATION_TYPE_INVALID') END;\n  SELECT CASE WHEN NOT json_valid(NEW.subject_refs_json) OR json_type(NEW.subject_refs_json) != 'object' THEN RAISE(ABORT, 'NOTIFICATION_REFS_INVALID') END;\n  SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM projects p WHERE p.id = NEW.project_id AND p.organization_id = NEW.organization_id) THEN RAISE(ABORT, 'NOTIFICATION_ORGANIZATION_INVALID') END;\n  SELECT CASE WHEN NEW.in_app_visible NOT IN (0, 1) THEN RAISE(ABORT, 'NOTIFICATION_VISIBILITY_INVALID') END;\nEND",
      "CREATE TRIGGER validate_notification_preferences_insert BEFORE INSERT ON notification_preferences BEGIN\n  SELECT CASE WHEN NEW.in_app_enabled NOT IN (0, 1) OR NEW.email_enabled NOT IN (0, 1) OR NOT json_valid(NEW.event_types_json) OR json_type(NEW.event_types_json) != 'array' OR EXISTS (SELECT 1 FROM json_each(NEW.event_types_json) WHERE value NOT IN ('review_requested', 'adjustment_requested', 'approval_completed', 'conflict_detected')) THEN RAISE(ABORT, 'NOTIFICATION_PREFERENCES_INVALID') END;\nEND",
      "CREATE TRIGGER validate_notification_preferences_update BEFORE UPDATE ON notification_preferences BEGIN\n  SELECT CASE WHEN NEW.in_app_enabled NOT IN (0, 1) OR NEW.email_enabled NOT IN (0, 1) OR NOT json_valid(NEW.event_types_json) OR json_type(NEW.event_types_json) != 'array' OR EXISTS (SELECT 1 FROM json_each(NEW.event_types_json) WHERE value NOT IN ('review_requested', 'adjustment_requested', 'approval_completed', 'conflict_detected')) THEN RAISE(ABORT, 'NOTIFICATION_PREFERENCES_INVALID') END;\nEND",
      "CREATE TRIGGER validate_email_outbox_insert BEFORE INSERT ON notification_email_outbox BEGIN\n  SELECT CASE WHEN NOT json_valid(NEW.subject_refs_json) OR json_type(NEW.subject_refs_json) != 'object' THEN RAISE(ABORT, 'EMAIL_OUTBOX_REFS_INVALID') END;\n  SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM notifications n WHERE n.id = NEW.notification_id AND n.body_code = NEW.body_code AND n.subject_refs_json = NEW.subject_refs_json) THEN RAISE(ABORT, 'EMAIL_OUTBOX_NOTIFICATION_INVALID') END;\nEND",
      "CREATE TRIGGER validate_email_outbox_update BEFORE UPDATE ON notification_email_outbox BEGIN\n  SELECT CASE WHEN NOT json_valid(NEW.subject_refs_json) OR json_type(NEW.subject_refs_json) != 'object' THEN RAISE(ABORT, 'EMAIL_OUTBOX_REFS_INVALID') END;\n  SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM notifications n WHERE n.id = NEW.notification_id AND n.body_code = NEW.body_code AND n.subject_refs_json = NEW.subject_refs_json) THEN RAISE(ABORT, 'EMAIL_OUTBOX_NOTIFICATION_INVALID') END;\nEND"
    ]
  },
  {
    "version": 8,
    "name": "event_day_runbooks",
    "checksum": "60c2ced659cdc107b6fb8d5eb0d80d70074f7a7cc903596404d435d7a4d3158b",
    "destructive": false,
    "requiresProjectExport": false,
    "statements": [
      "CREATE TABLE event_day_runbooks (\n  id TEXT PRIMARY KEY,\n  organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,\n  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n  schema_version INTEGER NOT NULL CHECK (schema_version = 1),\n  source_plan_id TEXT NOT NULL CHECK (length(source_plan_id) > 0),\n  source_plan_version TEXT NOT NULL CHECK (length(source_plan_version) > 0),\n  source_plan_fingerprint TEXT NOT NULL CHECK (length(source_plan_fingerprint) > 0),\n  source_validation_id TEXT,\n  source_validation_fingerprint TEXT,\n  source_activity_ledger_head_hash TEXT NOT NULL CHECK (length(source_activity_ledger_head_hash) > 0),\n  definition_json TEXT NOT NULL CHECK (json_valid(definition_json) AND json_type(definition_json) = 'object'),\n  frozen_by TEXT NOT NULL CHECK (length(frozen_by) > 0),\n  frozen_at TEXT NOT NULL,\n  updated_at TEXT NOT NULL,\n  sequence INTEGER NOT NULL DEFAULT 0 CHECK (sequence >= 0),\n  ledger_head_hash TEXT NOT NULL CHECK (length(ledger_head_hash) > 0),\n  UNIQUE (id, organization_id, project_id),\n  FOREIGN KEY (project_id, organization_id) REFERENCES projects(id, organization_id) ON DELETE CASCADE\n)",
      "CREATE TABLE event_day_runbook_tasks (\n  runbook_id TEXT NOT NULL,\n  id TEXT NOT NULL,\n  organization_id TEXT NOT NULL,\n  project_id TEXT NOT NULL,\n  phase_id TEXT NOT NULL CHECK (length(phase_id) > 0),\n  owner_role TEXT CHECK (owner_role IS NULL OR length(owner_role) > 0),\n  definition_json TEXT NOT NULL CHECK (json_valid(definition_json) AND json_type(definition_json) = 'object'),\n  status TEXT NOT NULL CHECK (length(status) > 0),\n  task_revision INTEGER NOT NULL DEFAULT 0 CHECK (task_revision >= 0),\n  last_transition_id TEXT,\n  updated_at TEXT NOT NULL,\n  PRIMARY KEY (runbook_id, id),\n  UNIQUE (runbook_id, id, organization_id, project_id),\n  FOREIGN KEY (runbook_id, organization_id, project_id) REFERENCES event_day_runbooks(id, organization_id, project_id) ON DELETE CASCADE\n)",
      "CREATE TABLE event_day_runbook_transitions (\n  id TEXT PRIMARY KEY,\n  runbook_id TEXT NOT NULL,\n  task_id TEXT NOT NULL,\n  organization_id TEXT NOT NULL,\n  project_id TEXT NOT NULL,\n  runbook_sequence INTEGER NOT NULL CHECK (runbook_sequence >= 1),\n  expected_task_revision INTEGER NOT NULL CHECK (expected_task_revision >= 0),\n  task_revision INTEGER NOT NULL CHECK (task_revision = expected_task_revision + 1),\n  from_status TEXT NOT NULL CHECK (length(from_status) > 0),\n  to_status TEXT NOT NULL CHECK (length(to_status) > 0),\n  actor_type TEXT NOT NULL CHECK (actor_type IN ('human', 'agent', 'system')),\n  actor_id TEXT NOT NULL CHECK (length(actor_id) > 0),\n  source TEXT NOT NULL CHECK (source IN ('studio', 'webmcp', 'mcp', 'system', 'agent-tool')),\n  session_id TEXT NOT NULL CHECK (length(session_id) > 0),\n  reason_code TEXT CHECK (reason_code IS NULL OR length(reason_code) > 0),\n  client_id TEXT NOT NULL CHECK (length(client_id) > 0),\n  client_sequence INTEGER NOT NULL CHECK (client_sequence >= 1),\n  client_occurred_at TEXT NOT NULL CHECK (length(client_occurred_at) > 0),\n  accepted_at TEXT NOT NULL,\n  evidence_json TEXT NOT NULL CHECK (json_valid(evidence_json) AND json_type(evidence_json) = 'array'),\n  idempotency_key TEXT NOT NULL CHECK (length(idempotency_key) > 0),\n  input_fingerprint TEXT NOT NULL CHECK (length(input_fingerprint) > 0),\n  correlation_id TEXT NOT NULL CHECK (length(correlation_id) > 0),\n  UNIQUE (runbook_id, runbook_sequence),\n  UNIQUE (runbook_id, idempotency_key),\n  UNIQUE (runbook_id, client_id, client_sequence),\n  UNIQUE (runbook_id, id, organization_id, project_id),\n  FOREIGN KEY (runbook_id, task_id, organization_id, project_id) REFERENCES event_day_runbook_tasks(runbook_id, id, organization_id, project_id) ON DELETE CASCADE\n)",
      "CREATE TABLE event_day_runbook_ledger (\n  id TEXT PRIMARY KEY,\n  runbook_id TEXT NOT NULL,\n  transition_id TEXT NOT NULL,\n  organization_id TEXT NOT NULL,\n  project_id TEXT NOT NULL,\n  schema_version INTEGER NOT NULL CHECK (schema_version = 1),\n  sequence INTEGER NOT NULL CHECK (sequence >= 1),\n  event_type TEXT NOT NULL CHECK (event_type = 'runbook.task_transitioned'),\n  actor_type TEXT NOT NULL CHECK (actor_type IN ('human', 'agent', 'system')),\n  actor_id TEXT NOT NULL CHECK (length(actor_id) > 0),\n  source TEXT NOT NULL CHECK (source IN ('studio', 'webmcp', 'mcp', 'system', 'agent-tool')),\n  session_id TEXT NOT NULL CHECK (length(session_id) > 0),\n  occurred_at TEXT NOT NULL,\n  details_json TEXT NOT NULL CHECK (json_valid(details_json) AND json_type(details_json) = 'object'),\n  previous_hash TEXT NOT NULL CHECK (length(previous_hash) > 0),\n  hash TEXT NOT NULL CHECK (length(hash) > 0),\n  UNIQUE (runbook_id, sequence),\n  UNIQUE (runbook_id, transition_id),\n  UNIQUE (runbook_id, id, organization_id, project_id),\n  FOREIGN KEY (runbook_id, transition_id, organization_id, project_id) REFERENCES event_day_runbook_transitions(runbook_id, id, organization_id, project_id) ON DELETE CASCADE\n)",
      "CREATE TABLE event_day_runbook_receipts (\n  id TEXT PRIMARY KEY,\n  runbook_id TEXT NOT NULL,\n  transition_id TEXT NOT NULL,\n  organization_id TEXT NOT NULL,\n  project_id TEXT NOT NULL,\n  idempotency_key TEXT NOT NULL CHECK (length(idempotency_key) > 0),\n  input_fingerprint TEXT NOT NULL CHECK (length(input_fingerprint) > 0),\n  correlation_id TEXT NOT NULL CHECK (length(correlation_id) > 0),\n  result_json TEXT NOT NULL CHECK (json_valid(result_json) AND json_type(result_json) = 'object'),\n  occurred_at TEXT NOT NULL,\n  UNIQUE (runbook_id, idempotency_key),\n  UNIQUE (runbook_id, transition_id),\n  FOREIGN KEY (runbook_id, transition_id, organization_id, project_id) REFERENCES event_day_runbook_transitions(runbook_id, id, organization_id, project_id) ON DELETE CASCADE\n)",
      "CREATE INDEX idx_event_day_runbooks_project ON event_day_runbooks(organization_id, project_id, frozen_at DESC)",
      "CREATE INDEX idx_event_day_runbook_tasks_view ON event_day_runbook_tasks(runbook_id, owner_role, phase_id, status, id)",
      "CREATE INDEX idx_event_day_runbook_transitions_cursor ON event_day_runbook_transitions(runbook_id, runbook_sequence)",
      "CREATE TRIGGER validate_event_day_runbook_update BEFORE UPDATE ON event_day_runbooks BEGIN\n  SELECT CASE WHEN NEW.organization_id != OLD.organization_id OR NEW.project_id != OLD.project_id OR NEW.schema_version != OLD.schema_version OR NEW.source_plan_id != OLD.source_plan_id OR NEW.source_plan_version != OLD.source_plan_version OR NEW.source_plan_fingerprint != OLD.source_plan_fingerprint OR NOT (NEW.source_validation_id IS OLD.source_validation_id) OR NOT (NEW.source_validation_fingerprint IS OLD.source_validation_fingerprint) OR NEW.source_activity_ledger_head_hash != OLD.source_activity_ledger_head_hash OR NEW.definition_json != OLD.definition_json OR NEW.frozen_by != OLD.frozen_by OR NEW.frozen_at != OLD.frozen_at THEN RAISE(ABORT, 'RUNBOOK_BASELINE_IMMUTABLE') END;\n  SELECT CASE WHEN NOT ((NEW.sequence = OLD.sequence AND NEW.ledger_head_hash = OLD.ledger_head_hash) OR (NEW.sequence = OLD.sequence + 1 AND EXISTS (SELECT 1 FROM event_day_runbook_ledger l WHERE l.runbook_id = NEW.id AND l.organization_id = NEW.organization_id AND l.project_id = NEW.project_id AND l.sequence = NEW.sequence AND l.previous_hash = OLD.ledger_head_hash AND l.hash = NEW.ledger_head_hash))) THEN RAISE(ABORT, 'RUNBOOK_SEQUENCE_INVALID') END;\nEND",
      "CREATE TRIGGER validate_event_day_runbook_task_insert BEFORE INSERT ON event_day_runbook_tasks BEGIN\n  SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM event_day_runbooks r WHERE r.id = NEW.runbook_id AND r.organization_id = NEW.organization_id AND r.project_id = NEW.project_id AND r.sequence = 0 AND r.ledger_head_hash = r.source_activity_ledger_head_hash) THEN RAISE(ABORT, 'RUNBOOK_TASK_BASELINE_INVALID') END;\nEND",
      "CREATE TRIGGER validate_event_day_runbook_task_update BEFORE UPDATE ON event_day_runbook_tasks BEGIN\n  SELECT CASE WHEN NEW.runbook_id != OLD.runbook_id OR NEW.id != OLD.id OR NEW.organization_id != OLD.organization_id OR NEW.project_id != OLD.project_id OR NEW.phase_id != OLD.phase_id OR NOT (NEW.owner_role IS OLD.owner_role) OR NEW.definition_json != OLD.definition_json THEN RAISE(ABORT, 'RUNBOOK_TASK_DEFINITION_IMMUTABLE') END;\n  SELECT CASE WHEN NEW.task_revision != OLD.task_revision + 1 OR NEW.last_transition_id IS NULL THEN RAISE(ABORT, 'RUNBOOK_TASK_REVISION_INVALID') END;\n  SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM event_day_runbook_transitions t WHERE t.runbook_id = NEW.runbook_id AND t.id = NEW.last_transition_id AND t.task_id = NEW.id AND t.task_revision = NEW.task_revision AND t.to_status = NEW.status) THEN RAISE(ABORT, 'RUNBOOK_TASK_TRANSITION_INVALID') END;\nEND",
      "CREATE TRIGGER validate_event_day_runbook_transition_insert BEFORE INSERT ON event_day_runbook_transitions BEGIN\n  SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM event_day_runbook_tasks t WHERE t.runbook_id = NEW.runbook_id AND t.id = NEW.task_id AND t.organization_id = NEW.organization_id AND t.project_id = NEW.project_id AND t.task_revision = NEW.expected_task_revision AND t.status = NEW.from_status) THEN RAISE(ABORT, 'RUNBOOK_TASK_REVISION_CONFLICT') END;\n  SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM event_day_runbooks r WHERE r.id = NEW.runbook_id AND r.organization_id = NEW.organization_id AND r.project_id = NEW.project_id AND r.sequence + 1 = NEW.runbook_sequence) THEN RAISE(ABORT, 'RUNBOOK_SEQUENCE_CONFLICT') END;\nEND",
      "CREATE TRIGGER reject_event_day_runbook_transition_update BEFORE UPDATE ON event_day_runbook_transitions BEGIN\n  SELECT RAISE(ABORT, 'RUNBOOK_TRANSITION_APPEND_ONLY');\nEND",
      "CREATE TRIGGER reject_event_day_runbook_transition_delete BEFORE DELETE ON event_day_runbook_transitions BEGIN\n  SELECT RAISE(ABORT, 'RUNBOOK_TRANSITION_APPEND_ONLY');\nEND",
      "CREATE TRIGGER validate_event_day_runbook_ledger_insert BEFORE INSERT ON event_day_runbook_ledger BEGIN\n  SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM event_day_runbook_transitions t WHERE t.runbook_id = NEW.runbook_id AND t.id = NEW.transition_id AND t.organization_id = NEW.organization_id AND t.project_id = NEW.project_id AND t.runbook_sequence = NEW.sequence AND t.actor_type = NEW.actor_type AND t.actor_id = NEW.actor_id AND t.source = NEW.source AND t.session_id = NEW.session_id AND t.accepted_at = NEW.occurred_at) THEN RAISE(ABORT, 'RUNBOOK_LEDGER_TRANSITION_INVALID') END;\n  SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM event_day_runbooks r WHERE r.id = NEW.runbook_id AND r.organization_id = NEW.organization_id AND r.project_id = NEW.project_id AND r.ledger_head_hash = NEW.previous_hash) THEN RAISE(ABORT, 'RUNBOOK_LEDGER_PREVIOUS_HASH_INVALID') END;\nEND",
      "CREATE TRIGGER reject_event_day_runbook_ledger_update BEFORE UPDATE ON event_day_runbook_ledger BEGIN\n  SELECT RAISE(ABORT, 'RUNBOOK_LEDGER_APPEND_ONLY');\nEND",
      "CREATE TRIGGER reject_event_day_runbook_ledger_delete BEFORE DELETE ON event_day_runbook_ledger BEGIN\n  SELECT RAISE(ABORT, 'RUNBOOK_LEDGER_APPEND_ONLY');\nEND",
      "CREATE TRIGGER validate_event_day_runbook_receipt_insert BEFORE INSERT ON event_day_runbook_receipts BEGIN\n  SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM event_day_runbook_transitions t WHERE t.runbook_id = NEW.runbook_id AND t.id = NEW.transition_id AND t.organization_id = NEW.organization_id AND t.project_id = NEW.project_id AND t.idempotency_key = NEW.idempotency_key AND t.input_fingerprint = NEW.input_fingerprint AND t.correlation_id = NEW.correlation_id) THEN RAISE(ABORT, 'RUNBOOK_RECEIPT_TRANSITION_INVALID') END;\nEND",
      "CREATE TRIGGER reject_event_day_runbook_receipt_update BEFORE UPDATE ON event_day_runbook_receipts BEGIN\n  SELECT RAISE(ABORT, 'RUNBOOK_RECEIPT_APPEND_ONLY');\nEND",
      "CREATE TRIGGER reject_event_day_runbook_receipt_delete BEFORE DELETE ON event_day_runbook_receipts BEGIN\n  SELECT RAISE(ABORT, 'RUNBOOK_RECEIPT_APPEND_ONLY');\nEND"
    ]
  },
  {
    "version": 9,
    "name": "live_occupancy",
    "checksum": "1ce0ac407378f795c8a4a2e667574cb1e79d89bd6be06d1d8d24cde8690b0222",
    "destructive": false,
    "requiresProjectExport": false,
    "statements": [
      "CREATE TABLE live_occupancy_monitors (\n  id TEXT PRIMARY KEY,\n  organization_id TEXT NOT NULL,\n  project_id TEXT NOT NULL,\n  runbook_id TEXT NOT NULL,\n  schema_version INTEGER NOT NULL CHECK (schema_version = 1),\n  baseline_fingerprint TEXT NOT NULL CHECK (length(baseline_fingerprint) > 0),\n  baseline_json TEXT NOT NULL CHECK (json_valid(baseline_json) AND json_type(baseline_json) = 'object'),\n  monitor_json TEXT NOT NULL CHECK (json_valid(monitor_json) AND json_type(monitor_json) = 'object'),\n  revision INTEGER NOT NULL CHECK (revision >= 0),\n  ledger_head_hash TEXT NOT NULL CHECK (length(ledger_head_hash) > 0),\n  created_at TEXT NOT NULL,\n  updated_at TEXT NOT NULL,\n  UNIQUE (runbook_id, organization_id, project_id),\n  FOREIGN KEY (runbook_id, organization_id, project_id) REFERENCES event_day_runbooks(id, organization_id, project_id) ON DELETE CASCADE\n)",
      "CREATE INDEX idx_live_occupancy_project ON live_occupancy_monitors(organization_id, project_id, updated_at DESC)",
      "CREATE TRIGGER validate_live_occupancy_update BEFORE UPDATE ON live_occupancy_monitors BEGIN\n  SELECT CASE WHEN NEW.organization_id != OLD.organization_id OR NEW.project_id != OLD.project_id OR NEW.runbook_id != OLD.runbook_id OR NEW.schema_version != OLD.schema_version OR NEW.baseline_fingerprint != OLD.baseline_fingerprint OR NEW.baseline_json != OLD.baseline_json OR NEW.created_at != OLD.created_at THEN RAISE(ABORT, 'OCCUPANCY_BASELINE_IMMUTABLE') END;\n  SELECT CASE WHEN NEW.revision != OLD.revision + 1 THEN RAISE(ABORT, 'OCCUPANCY_REVISION_INVALID') END;\nEND"
    ]
  }
]);
export const DATABASE_SCHEMA_VERSION = 9;
