// Generated by scripts/generate-db-migrations.mjs. Do not edit.
export const DATABASE_MIGRATIONS = Object.freeze([
  {
    "version": 1,
    "name": "initial_projects",
    "checksum": "35c5016e7ae358e1a8f477845b742f6738661a43959baf78dfc8d3d98deabc18",
    "destructive": false,
    "requiresProjectExport": false,
    "statements": [
      "CREATE TABLE projects (\n  id TEXT PRIMARY KEY,\n  name TEXT NOT NULL,\n  active_plan_id TEXT NOT NULL,\n  created_at TEXT NOT NULL,\n  updated_at TEXT NOT NULL\n)",
      "CREATE TABLE project_states (\n  project_id TEXT PRIMARY KEY REFERENCES projects(id) ON DELETE CASCADE,\n  schema_version INTEGER NOT NULL,\n  snapshot_json TEXT NOT NULL,\n  updated_at TEXT NOT NULL\n)",
      "CREATE INDEX idx_projects_updated_at ON projects(updated_at DESC)"
    ]
  },
  {
    "version": 2,
    "name": "project_lifecycle",
    "checksum": "60b091a88ba6bfd1c5a327d7ba594e6c9d74e72579696e0057804bc9636e7f4b",
    "destructive": false,
    "requiresProjectExport": false,
    "statements": [
      "ALTER TABLE projects ADD COLUMN provenance_json TEXT",
      "ALTER TABLE projects ADD COLUMN archived_at TEXT",
      "ALTER TABLE projects ADD COLUMN deleted_at TEXT",
      "ALTER TABLE projects ADD COLUMN recovery_until TEXT",
      "ALTER TABLE projects ADD COLUMN pinned INTEGER NOT NULL DEFAULT 0",
      "ALTER TABLE projects ADD COLUMN last_opened_at TEXT"
    ]
  },
  {
    "version": 3,
    "name": "accounts_and_tenancy",
    "checksum": "9818dbe0d6e276af37e70d245f7c9558b1ad803458786ebef315e9af4ed10836",
    "destructive": false,
    "requiresProjectExport": false,
    "statements": [
      "CREATE TABLE users (\n  id TEXT PRIMARY KEY,\n  identity_provider TEXT NOT NULL,\n  provider_subject TEXT NOT NULL,\n  email TEXT NOT NULL,\n  display_name TEXT,\n  status TEXT NOT NULL DEFAULT 'active',\n  created_at TEXT NOT NULL,\n  updated_at TEXT NOT NULL,\n  deleted_at TEXT,\n  UNIQUE(identity_provider, provider_subject)\n)",
      "CREATE TABLE organizations (\n  id TEXT PRIMARY KEY,\n  name TEXT NOT NULL,\n  slug TEXT NOT NULL UNIQUE,\n  created_by TEXT NOT NULL REFERENCES users(id),\n  created_at TEXT NOT NULL,\n  updated_at TEXT NOT NULL,\n  deleted_at TEXT\n)",
      "CREATE TABLE organization_memberships (\n  organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,\n  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  roles_json TEXT NOT NULL,\n  status TEXT NOT NULL DEFAULT 'active',\n  created_at TEXT NOT NULL,\n  updated_at TEXT NOT NULL,\n  PRIMARY KEY (organization_id, user_id)\n)",
      "CREATE TABLE organization_invitations (\n  id TEXT PRIMARY KEY,\n  organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,\n  email TEXT NOT NULL,\n  roles_json TEXT NOT NULL,\n  token_hash TEXT NOT NULL UNIQUE,\n  invited_by TEXT NOT NULL REFERENCES users(id),\n  created_at TEXT NOT NULL,\n  expires_at TEXT NOT NULL,\n  accepted_at TEXT,\n  revoked_at TEXT\n)",
      "CREATE TABLE user_sessions (\n  id TEXT PRIMARY KEY,\n  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  created_at TEXT NOT NULL,\n  expires_at TEXT NOT NULL,\n  revoked_at TEXT,\n  last_seen_at TEXT NOT NULL\n)",
      "CREATE TABLE organization_audit_events (\n  id TEXT PRIMARY KEY,\n  organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,\n  event_type TEXT NOT NULL,\n  actor_user_id TEXT NOT NULL,\n  target_user_id TEXT,\n  details_json TEXT NOT NULL,\n  fingerprint TEXT NOT NULL,\n  occurred_at TEXT NOT NULL\n)",
      "CREATE TABLE account_deletion_requests (\n  id TEXT PRIMARY KEY,\n  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  requested_at TEXT NOT NULL,\n  completed_at TEXT,\n  status TEXT NOT NULL\n)",
      "ALTER TABLE projects ADD COLUMN organization_id TEXT REFERENCES organizations(id)",
      "INSERT INTO users (id, identity_provider, provider_subject, email, display_name, status, created_at, updated_at)\nSELECT 'user-legacy-migration', 'migration', 'legacy-project-owner', 'legacy-projects@venuemind.invalid', 'LEGACY', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP\nWHERE EXISTS (SELECT 1 FROM projects) AND NOT EXISTS (SELECT 1 FROM users WHERE id = 'user-legacy-migration')",
      "INSERT INTO organizations (id, name, slug, created_by, created_at, updated_at)\nSELECT 'org-legacy-migration', 'LEGACY', 'legacy-migration', 'user-legacy-migration', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP\nWHERE EXISTS (SELECT 1 FROM projects) AND NOT EXISTS (SELECT 1 FROM organizations WHERE id = 'org-legacy-migration')",
      "INSERT INTO organization_memberships (organization_id, user_id, roles_json, status, created_at, updated_at)\nSELECT 'org-legacy-migration', 'user-legacy-migration', '[\"organization-administrator\"]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP\nWHERE EXISTS (SELECT 1 FROM projects) AND NOT EXISTS (SELECT 1 FROM organization_memberships WHERE organization_id = 'org-legacy-migration' AND user_id = 'user-legacy-migration')",
      "UPDATE projects SET organization_id = 'org-legacy-migration' WHERE organization_id IS NULL",
      "CREATE INDEX idx_projects_organization_updated ON projects(organization_id, updated_at DESC)",
      "CREATE INDEX idx_memberships_user ON organization_memberships(user_id, status)",
      "CREATE INDEX idx_invitations_organization_email ON organization_invitations(organization_id, email)",
      "CREATE INDEX idx_sessions_user ON user_sessions(user_id, expires_at)",
      "CREATE INDEX idx_account_audit_organization ON organization_audit_events(organization_id, occurred_at DESC)"
    ]
  },
  {
    "version": 4,
    "name": "optimistic_concurrency",
    "checksum": "bfac1ab0c7d6320045da6af0863e094ff270087262d56fa8507ab414a59b169b",
    "destructive": false,
    "requiresProjectExport": false,
    "statements": [
      "ALTER TABLE projects ADD COLUMN revision INTEGER NOT NULL DEFAULT 1",
      "ALTER TABLE projects ADD COLUMN write_token TEXT",
      "CREATE UNIQUE INDEX idx_projects_write_token ON projects(write_token) WHERE write_token IS NOT NULL"
    ]
  },
  {
    "version": 5,
    "name": "realtime_collaboration",
    "checksum": "9aaa50b1ee0f730ede2ba825a035471c2559cbd6dcb87524139822648478bea8",
    "destructive": false,
    "requiresProjectExport": false,
    "statements": [
      "CREATE TABLE project_collaboration_events (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,\n  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n  previous_event_id INTEGER,\n  event_type TEXT NOT NULL,\n  actor_user_id TEXT NOT NULL REFERENCES users(id),\n  session_id TEXT NOT NULL,\n  project_revision INTEGER NOT NULL,\n  payload_json TEXT NOT NULL,\n  occurred_at TEXT NOT NULL\n)",
      "CREATE INDEX idx_collaboration_events_project_cursor ON project_collaboration_events(organization_id, project_id, id)",
      "CREATE TABLE project_presence (\n  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n  organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,\n  session_id TEXT NOT NULL,\n  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  display_name TEXT NOT NULL,\n  plan_version TEXT NOT NULL,\n  focused_object_id TEXT,\n  viewport_json TEXT,\n  last_seen_at TEXT NOT NULL,\n  expires_at TEXT NOT NULL,\n  PRIMARY KEY (project_id, session_id)\n)",
      "CREATE INDEX idx_project_presence_expiry ON project_presence(organization_id, project_id, expires_at)"
    ]
  },
  {
    "version": 6,
    "name": "sharing_notifications",
    "checksum": "1ab7b3cf4cd5eaf27b317eddbda23c079128ff51c355389ee57dc605efcd8847",
    "destructive": false,
    "requiresProjectExport": false,
    "statements": [
      "CREATE UNIQUE INDEX idx_projects_id_organization ON projects(id, organization_id)",
      "CREATE TABLE project_share_links (\n  id TEXT PRIMARY KEY,\n  organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,\n  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n  proposal_id TEXT,\n  scope TEXT NOT NULL CHECK (scope IN ('read-only', 'reviewer')),\n  token_hash TEXT NOT NULL UNIQUE CHECK (length(token_hash) = 64 AND token_hash NOT GLOB '*[^0-9a-f]*'),\n  created_by TEXT NOT NULL REFERENCES users(id),\n  created_at TEXT NOT NULL,\n  expires_at TEXT NOT NULL CHECK (expires_at > created_at),\n  revoked_at TEXT,\n  revoked_by TEXT REFERENCES users(id),\n  CHECK ((scope = 'read-only' AND proposal_id IS NULL) OR (scope = 'reviewer' AND proposal_id IS NOT NULL AND length(proposal_id) > 0)),\n  CHECK ((revoked_at IS NULL AND revoked_by IS NULL) OR (revoked_at IS NOT NULL AND revoked_by IS NOT NULL)),\n  FOREIGN KEY (project_id, organization_id) REFERENCES projects(id, organization_id) ON DELETE CASCADE\n)",
      "CREATE INDEX idx_share_links_project ON project_share_links(organization_id, project_id, created_at DESC)",
      "CREATE TABLE notification_preferences (\n  user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,\n  in_app_enabled INTEGER NOT NULL DEFAULT 1 CHECK (in_app_enabled IN (0, 1)),\n  email_enabled INTEGER NOT NULL DEFAULT 0 CHECK (email_enabled IN (0, 1)),\n  event_types_json TEXT NOT NULL DEFAULT '[\"review_requested\",\"adjustment_requested\",\"approval_completed\",\"conflict_detected\"]' CHECK (json_valid(event_types_json) AND json_type(event_types_json) = 'array'),\n  updated_at TEXT NOT NULL\n)",
      "CREATE TABLE notifications (\n  id TEXT PRIMARY KEY,\n  organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,\n  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  event_type TEXT NOT NULL CHECK (event_type IN ('review_requested', 'adjustment_requested', 'approval_completed', 'conflict_detected')),\n  body_code TEXT NOT NULL CHECK (body_code = 'notification.' || event_type),\n  subject_refs_json TEXT NOT NULL CHECK (json_valid(subject_refs_json) AND json_type(subject_refs_json) = 'object'),\n  created_at TEXT NOT NULL,\n  read_at TEXT,\n  FOREIGN KEY (project_id, organization_id) REFERENCES projects(id, organization_id) ON DELETE CASCADE\n)",
      "CREATE INDEX idx_notifications_user_unread ON notifications(user_id, read_at, created_at DESC)",
      "CREATE TABLE notification_email_outbox (\n  id TEXT PRIMARY KEY,\n  notification_id TEXT NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,\n  recipient_email TEXT NOT NULL,\n  body_code TEXT NOT NULL,\n  subject_refs_json TEXT NOT NULL CHECK (json_valid(subject_refs_json) AND json_type(subject_refs_json) = 'object'),\n  created_at TEXT NOT NULL,\n  delivered_at TEXT,\n  failure_code TEXT\n)"
    ]
  }
]);
export const DATABASE_SCHEMA_VERSION = 6;
