export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    identity_provider TEXT NOT NULL,
    provider_subject TEXT NOT NULL,
    email TEXT NOT NULL,
    display_name TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT,
    UNIQUE(identity_provider, provider_subject)
  )`,
  `CREATE TABLE IF NOT EXISTS organizations (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    created_by TEXT NOT NULL REFERENCES users(id),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS organization_memberships (
    organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    roles_json TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (organization_id, user_id)
  )`,
  `CREATE TABLE IF NOT EXISTS organization_invitations (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    roles_json TEXT NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,
    invited_by TEXT NOT NULL REFERENCES users(id),
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    accepted_at TEXT,
    revoked_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS user_sessions (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    revoked_at TEXT,
    last_seen_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS organization_audit_events (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    actor_user_id TEXT NOT NULL REFERENCES users(id),
    target_user_id TEXT,
    details_json TEXT NOT NULL,
    fingerprint TEXT NOT NULL,
    occurred_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS account_deletion_requests (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    requested_at TEXT NOT NULL,
    completed_at TEXT,
    status TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS projects (
    id TEXT PRIMARY KEY,
    organization_id TEXT REFERENCES organizations(id),
    name TEXT NOT NULL,
    active_plan_id TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    provenance_json TEXT,
    archived_at TEXT,
    deleted_at TEXT,
    recovery_until TEXT,
    pinned INTEGER NOT NULL DEFAULT 0,
    last_opened_at TEXT,
    revision INTEGER NOT NULL DEFAULT 1,
    write_token TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS project_states (
    project_id TEXT PRIMARY KEY REFERENCES projects(id) ON DELETE CASCADE,
    schema_version INTEGER NOT NULL,
    snapshot_json TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS project_collaboration_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    previous_event_id INTEGER,
    event_type TEXT NOT NULL,
    actor_user_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    project_revision INTEGER NOT NULL,
    payload_json TEXT NOT NULL,
    occurred_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS project_presence (
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    session_id TEXT NOT NULL,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    display_name TEXT NOT NULL,
    plan_version TEXT NOT NULL,
    focused_object_id TEXT,
    viewport_json TEXT,
    last_seen_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    PRIMARY KEY (project_id, session_id)
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_projects_id_organization
    ON projects(id, organization_id)`,
  `CREATE TABLE IF NOT EXISTS project_share_links (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    proposal_id TEXT,
    scope TEXT NOT NULL CHECK (scope IN ('read-only', 'reviewer')),
    token_hash TEXT NOT NULL UNIQUE CHECK (length(token_hash) = 64 AND token_hash NOT GLOB '*[^0-9a-f]*'),
    created_by TEXT NOT NULL REFERENCES users(id),
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL CHECK (expires_at > created_at),
    revoked_at TEXT,
    revoked_by TEXT REFERENCES users(id),
    lifecycle_state TEXT NOT NULL DEFAULT 'active' CHECK (lifecycle_state IN ('pending-create', 'active', 'pending-revoke', 'revoked')),
    creation_ledgered_at TEXT,
    revocation_ledgered_at TEXT,
    operation_attempts INTEGER NOT NULL DEFAULT 0,
    last_operation_error TEXT,
    CHECK ((scope = 'read-only' AND proposal_id IS NULL) OR (scope = 'reviewer' AND proposal_id IS NOT NULL AND length(proposal_id) > 0)),
    CHECK ((revoked_at IS NULL AND revoked_by IS NULL) OR (revoked_at IS NOT NULL AND revoked_by IS NOT NULL)),
    FOREIGN KEY (project_id, organization_id) REFERENCES projects(id, organization_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS notification_preferences (
    user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    in_app_enabled INTEGER NOT NULL DEFAULT 1 CHECK (in_app_enabled IN (0, 1)),
    email_enabled INTEGER NOT NULL DEFAULT 0 CHECK (email_enabled IN (0, 1)),
    event_types_json TEXT NOT NULL DEFAULT '["review_requested","adjustment_requested","approval_completed","conflict_detected"]' CHECK (json_valid(event_types_json) AND json_type(event_types_json) = 'array'),
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS notifications (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL CHECK (event_type IN ('review_requested', 'adjustment_requested', 'approval_completed', 'conflict_detected')),
    body_code TEXT NOT NULL CHECK (body_code = 'notification.' || event_type),
    subject_refs_json TEXT NOT NULL CHECK (json_valid(subject_refs_json) AND json_type(subject_refs_json) = 'object'),
    created_at TEXT NOT NULL,
    read_at TEXT,
    in_app_visible INTEGER NOT NULL DEFAULT 1 CHECK (in_app_visible IN (0, 1)),
    FOREIGN KEY (project_id, organization_id) REFERENCES projects(id, organization_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS notification_email_outbox (
    id TEXT PRIMARY KEY,
    notification_id TEXT NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
    recipient_email TEXT NOT NULL,
    body_code TEXT NOT NULL,
    subject_refs_json TEXT NOT NULL CHECK (json_valid(subject_refs_json) AND json_type(subject_refs_json) = 'object'),
    created_at TEXT NOT NULL,
    delivered_at TEXT,
    failure_code TEXT,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_attempt_at TEXT,
    lease_token TEXT,
    lease_expires_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS event_day_runbooks (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    schema_version INTEGER NOT NULL CHECK (schema_version = 1),
    source_plan_id TEXT NOT NULL CHECK (length(source_plan_id) > 0),
    source_plan_version TEXT NOT NULL CHECK (length(source_plan_version) > 0),
    source_plan_fingerprint TEXT NOT NULL CHECK (length(source_plan_fingerprint) > 0),
    source_validation_id TEXT,
    source_validation_fingerprint TEXT,
    source_activity_ledger_head_hash TEXT NOT NULL CHECK (length(source_activity_ledger_head_hash) > 0),
    definition_json TEXT NOT NULL CHECK (json_valid(definition_json) AND json_type(definition_json) = 'object'),
    frozen_by TEXT NOT NULL CHECK (length(frozen_by) > 0),
    frozen_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    sequence INTEGER NOT NULL DEFAULT 0 CHECK (sequence >= 0),
    ledger_head_hash TEXT NOT NULL CHECK (length(ledger_head_hash) > 0),
    UNIQUE (id, organization_id, project_id),
    FOREIGN KEY (project_id, organization_id) REFERENCES projects(id, organization_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS event_day_runbook_tasks (
    runbook_id TEXT NOT NULL,
    id TEXT NOT NULL,
    organization_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    phase_id TEXT NOT NULL CHECK (length(phase_id) > 0),
    owner_role TEXT CHECK (owner_role IS NULL OR length(owner_role) > 0),
    definition_json TEXT NOT NULL CHECK (json_valid(definition_json) AND json_type(definition_json) = 'object'),
    status TEXT NOT NULL CHECK (length(status) > 0),
    task_revision INTEGER NOT NULL DEFAULT 0 CHECK (task_revision >= 0),
    last_transition_id TEXT,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (runbook_id, id),
    UNIQUE (runbook_id, id, organization_id, project_id),
    FOREIGN KEY (runbook_id, organization_id, project_id) REFERENCES event_day_runbooks(id, organization_id, project_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS event_day_runbook_transitions (
    id TEXT PRIMARY KEY,
    runbook_id TEXT NOT NULL,
    task_id TEXT NOT NULL,
    organization_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    runbook_sequence INTEGER NOT NULL CHECK (runbook_sequence >= 1),
    expected_task_revision INTEGER NOT NULL CHECK (expected_task_revision >= 0),
    task_revision INTEGER NOT NULL CHECK (task_revision = expected_task_revision + 1),
    from_status TEXT NOT NULL CHECK (length(from_status) > 0),
    to_status TEXT NOT NULL CHECK (length(to_status) > 0),
    actor_type TEXT NOT NULL CHECK (actor_type IN ('human', 'agent', 'system')),
    actor_id TEXT NOT NULL CHECK (length(actor_id) > 0),
    source TEXT NOT NULL CHECK (source IN ('studio', 'webmcp', 'mcp', 'system', 'agent-tool')),
    session_id TEXT NOT NULL CHECK (length(session_id) > 0),
    reason_code TEXT CHECK (reason_code IS NULL OR length(reason_code) > 0),
    client_id TEXT NOT NULL CHECK (length(client_id) > 0),
    client_sequence INTEGER NOT NULL CHECK (client_sequence >= 1),
    client_occurred_at TEXT NOT NULL CHECK (length(client_occurred_at) > 0),
    accepted_at TEXT NOT NULL,
    evidence_json TEXT NOT NULL CHECK (json_valid(evidence_json) AND json_type(evidence_json) = 'array'),
    idempotency_key TEXT NOT NULL CHECK (length(idempotency_key) > 0),
    input_fingerprint TEXT NOT NULL CHECK (length(input_fingerprint) > 0),
    correlation_id TEXT NOT NULL CHECK (length(correlation_id) > 0),
    UNIQUE (runbook_id, runbook_sequence),
    UNIQUE (runbook_id, idempotency_key),
    UNIQUE (runbook_id, client_id, client_sequence),
    UNIQUE (runbook_id, id, organization_id, project_id),
    FOREIGN KEY (runbook_id, task_id, organization_id, project_id) REFERENCES event_day_runbook_tasks(runbook_id, id, organization_id, project_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS event_day_runbook_ledger (
    id TEXT PRIMARY KEY,
    runbook_id TEXT NOT NULL,
    transition_id TEXT NOT NULL,
    organization_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    schema_version INTEGER NOT NULL CHECK (schema_version = 1),
    sequence INTEGER NOT NULL CHECK (sequence >= 1),
    event_type TEXT NOT NULL CHECK (event_type = 'runbook.task_transitioned'),
    actor_type TEXT NOT NULL CHECK (actor_type IN ('human', 'agent', 'system')),
    actor_id TEXT NOT NULL CHECK (length(actor_id) > 0),
    source TEXT NOT NULL CHECK (source IN ('studio', 'webmcp', 'mcp', 'system', 'agent-tool')),
    session_id TEXT NOT NULL CHECK (length(session_id) > 0),
    occurred_at TEXT NOT NULL,
    details_json TEXT NOT NULL CHECK (json_valid(details_json) AND json_type(details_json) = 'object'),
    previous_hash TEXT NOT NULL CHECK (length(previous_hash) > 0),
    hash TEXT NOT NULL CHECK (length(hash) > 0),
    UNIQUE (runbook_id, sequence),
    UNIQUE (runbook_id, transition_id),
    UNIQUE (runbook_id, id, organization_id, project_id),
    FOREIGN KEY (runbook_id, transition_id, organization_id, project_id) REFERENCES event_day_runbook_transitions(runbook_id, id, organization_id, project_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS event_day_runbook_receipts (
    id TEXT PRIMARY KEY,
    runbook_id TEXT NOT NULL,
    transition_id TEXT NOT NULL,
    organization_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    idempotency_key TEXT NOT NULL CHECK (length(idempotency_key) > 0),
    input_fingerprint TEXT NOT NULL CHECK (length(input_fingerprint) > 0),
    correlation_id TEXT NOT NULL CHECK (length(correlation_id) > 0),
    result_json TEXT NOT NULL CHECK (json_valid(result_json) AND json_type(result_json) = 'object'),
    occurred_at TEXT NOT NULL,
    UNIQUE (runbook_id, idempotency_key),
    UNIQUE (runbook_id, transition_id),
    FOREIGN KEY (runbook_id, transition_id, organization_id, project_id) REFERENCES event_day_runbook_transitions(runbook_id, id, organization_id, project_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS live_occupancy_monitors (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    runbook_id TEXT NOT NULL,
    schema_version INTEGER NOT NULL CHECK (schema_version = 1),
    baseline_fingerprint TEXT NOT NULL CHECK (length(baseline_fingerprint) > 0),
    baseline_json TEXT NOT NULL CHECK (json_valid(baseline_json) AND json_type(baseline_json) = 'object'),
    monitor_json TEXT NOT NULL CHECK (json_valid(monitor_json) AND json_type(monitor_json) = 'object'),
    revision INTEGER NOT NULL CHECK (revision >= 0),
    ledger_head_hash TEXT NOT NULL CHECK (length(ledger_head_hash) > 0),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (runbook_id, organization_id, project_id),
    FOREIGN KEY (runbook_id, organization_id, project_id) REFERENCES event_day_runbooks(id, organization_id, project_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS event_day_incident_registers (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    runbook_id TEXT NOT NULL,
    schema_version INTEGER NOT NULL CHECK (schema_version = 1),
    baseline_fingerprint TEXT NOT NULL CHECK (length(baseline_fingerprint) > 0),
    baseline_json TEXT NOT NULL CHECK (json_valid(baseline_json) AND json_type(baseline_json) = 'object'),
    register_json TEXT NOT NULL CHECK (json_valid(register_json) AND json_type(register_json) = 'object'),
    revision INTEGER NOT NULL CHECK (revision >= 0),
    ledger_head_hash TEXT NOT NULL CHECK (length(ledger_head_hash) > 0),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (runbook_id, organization_id, project_id),
    FOREIGN KEY (runbook_id, organization_id, project_id) REFERENCES event_day_runbooks(id, organization_id, project_id) ON DELETE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS idx_projects_updated_at
    ON projects(updated_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_projects_organization_updated
    ON projects(organization_id, updated_at DESC)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_projects_write_token
    ON projects(write_token) WHERE write_token IS NOT NULL`,
  `CREATE INDEX IF NOT EXISTS idx_collaboration_events_project_cursor
    ON project_collaboration_events(organization_id, project_id, id)`,
  `CREATE INDEX IF NOT EXISTS idx_project_presence_expiry
    ON project_presence(organization_id, project_id, expires_at)`,
  `CREATE INDEX IF NOT EXISTS idx_share_links_project
    ON project_share_links(organization_id, project_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_share_links_pending
    ON project_share_links(lifecycle_state, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_notifications_user_unread
    ON notifications(user_id, read_at, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_email_outbox_pending
    ON notification_email_outbox(delivered_at, lease_expires_at, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_event_day_runbooks_project
    ON event_day_runbooks(organization_id, project_id, frozen_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_event_day_runbook_tasks_view
    ON event_day_runbook_tasks(runbook_id, owner_role, phase_id, status, id)`,
  `CREATE INDEX IF NOT EXISTS idx_event_day_runbook_transitions_cursor
    ON event_day_runbook_transitions(runbook_id, runbook_sequence)`,
  `CREATE INDEX IF NOT EXISTS idx_live_occupancy_project
    ON live_occupancy_monitors(organization_id, project_id, updated_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_event_day_incident_registers_project
    ON event_day_incident_registers(organization_id, project_id, updated_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_memberships_user
    ON organization_memberships(user_id, status)`,
  `CREATE INDEX IF NOT EXISTS idx_invitations_organization_email
    ON organization_invitations(organization_id, email)`,
  `CREATE INDEX IF NOT EXISTS idx_sessions_user
    ON user_sessions(user_id, expires_at)`,
  `CREATE INDEX IF NOT EXISTS idx_account_audit_organization
    ON organization_audit_events(organization_id, occurred_at DESC)`,
];
