import { applyDatabaseMigrations } from "./database-migrations.ts";
import { normalizeNotificationPreferences, shareLinkStatus } from "../src/domain/sharing.ts";

type D1Statement = { bind: (...values: unknown[]) => D1Statement; first: <T>() => Promise<T | null>; all: <T>() => Promise<{ results: T[] }>; run: () => Promise<unknown> };
type D1Database = { prepare: (sql: string) => D1Statement; batch: (statements: D1Statement[]) => Promise<unknown> };
const initialized = new WeakSet<object>();
async function ready(db: D1Database) { if (!initialized.has(db as object)) { await applyDatabaseMigrations(db as never); initialized.add(db as object); } }

const mapLink = (row: Record<string, unknown>) => ({
  id: String(row.id), organizationId: String(row.organization_id), projectId: String(row.project_id), proposalId: row.proposal_id ? String(row.proposal_id) : null,
  scope: String(row.scope), tokenHash: String(row.token_hash), createdBy: String(row.created_by), createdAt: String(row.created_at), expiresAt: String(row.expires_at),
  revokedAt: row.revoked_at ? String(row.revoked_at) : null, revokedBy: row.revoked_by ? String(row.revoked_by) : null,
  lifecycleState: String(row.lifecycle_state ?? "active"), creationLedgeredAt: row.creation_ledgered_at ? String(row.creation_ledgered_at) : null,
  revocationLedgeredAt: row.revocation_ledgered_at ? String(row.revocation_ledgered_at) : null, operationAttempts: Number(row.operation_attempts ?? 0),
  lastOperationError: row.last_operation_error ? String(row.last_operation_error) : null,
});
const lifecycleStatus = (link, now) => link.lifecycleState === "pending-create" ? "pending" : ["pending-revoke", "revoked"].includes(link.lifecycleState) ? "revoked" : shareLinkStatus(link, now);
const mapNotification = (row: Record<string, unknown>) => ({ id: String(row.id), organizationId: String(row.organization_id), projectId: String(row.project_id), userId: String(row.user_id), eventType: String(row.event_type), bodyCode: String(row.body_code), refs: JSON.parse(String(row.subject_refs_json)), createdAt: String(row.created_at), readAt: row.read_at ? String(row.read_at) : null });
const mapEmail = (row: Record<string, unknown>) => ({ id: String(row.id), notificationId: String(row.notification_id), recipientEmail: String(row.recipient_email), bodyCode: String(row.body_code), refs: JSON.parse(String(row.subject_refs_json)), createdAt: String(row.created_at), attemptCount: Number(row.attempt_count ?? 0), leaseToken: row.lease_token ? String(row.lease_token) : null });
const preferencesFromRow = (row: Record<string, unknown>) => normalizeNotificationPreferences({ inAppEnabled: Boolean(row.in_app_enabled), emailEnabled: Boolean(row.email_enabled), eventTypes: JSON.parse(String(row.event_types_json)) });

export function createD1SharingRepository(db: D1Database) {
  return {
    async createLink(link: Record<string, unknown>) { await ready(db); await db.prepare("INSERT INTO project_share_links (id,organization_id,project_id,proposal_id,scope,token_hash,created_by,created_at,expires_at,lifecycle_state,creation_ledgered_at,revocation_ledgered_at,operation_attempts,last_operation_error) VALUES (?,?,?,?,?,?,?,?,?,'pending-create',NULL,NULL,0,NULL)").bind(link.id, link.organizationId, link.projectId, link.proposalId ?? null, link.scope, link.tokenHash, link.createdBy, link.createdAt, link.expiresAt).run(); return { ...link, lifecycleState: "pending-create", creationLedgeredAt: null, revocationLedgeredAt: null, operationAttempts: 0, lastOperationError: null }; },
    async listLinks(organizationId: string, projectId: string) { await ready(db); const { results } = await db.prepare("SELECT * FROM project_share_links WHERE organization_id=? AND project_id=? ORDER BY created_at DESC,id DESC").bind(organizationId, projectId).all<Record<string, unknown>>(); return results.map(mapLink); },
    async resolveLink(tokenHash: string, now: string) { await ready(db); const row = await db.prepare("SELECT * FROM project_share_links WHERE token_hash=?").bind(tokenHash).first<Record<string, unknown>>(); if (!row) return null; const link = mapLink(row); return { ...link, status: lifecycleStatus(link, now) }; },
    async pendingLinkOperations({ organizationId = null, projectId = null, linkId = null, limit = 100 } = {}) { await ready(db); const clauses = ["lifecycle_state IN ('pending-create','pending-revoke')"]; const values: unknown[] = []; if (organizationId) { clauses.push("organization_id=?"); values.push(organizationId); } if (projectId) { clauses.push("project_id=?"); values.push(projectId); } if (linkId) { clauses.push("id=?"); values.push(linkId); } values.push(Math.max(1, Math.min(100, Number(limit) || 100))); const { results } = await db.prepare(`SELECT * FROM project_share_links WHERE ${clauses.join(" AND ")} ORDER BY created_at,id LIMIT ?`).bind(...values).all<Record<string, unknown>>(); return results.map(mapLink); },
    async markLinkCreated(linkId: string, ledgeredAt: string) { await ready(db); const row = await db.prepare("UPDATE project_share_links SET lifecycle_state='active',creation_ledgered_at=?,last_operation_error=NULL WHERE id=? AND lifecycle_state='pending-create' RETURNING *").bind(ledgeredAt, linkId).first<Record<string, unknown>>(); return row ? mapLink(row) : null; },
    async beginRevoke(organizationId: string, projectId: string, linkId: string, userId: string, revokedAt: string) { await ready(db); const updated = await db.prepare("UPDATE project_share_links SET lifecycle_state='pending-revoke',revoked_at=?,revoked_by=?,last_operation_error=NULL WHERE id=? AND organization_id=? AND project_id=? AND lifecycle_state='active' RETURNING *").bind(revokedAt, userId, linkId, organizationId, projectId).first<Record<string, unknown>>(); if (updated) return { link: mapLink(updated), changed: true }; const row = await db.prepare("SELECT * FROM project_share_links WHERE id=? AND organization_id=? AND project_id=?").bind(linkId, organizationId, projectId).first<Record<string, unknown>>(); return row ? { link: mapLink(row), changed: false } : null; },
    async markLinkRevoked(linkId: string, ledgeredAt: string) { await ready(db); const row = await db.prepare("UPDATE project_share_links SET lifecycle_state='revoked',revocation_ledgered_at=?,last_operation_error=NULL WHERE id=? AND lifecycle_state='pending-revoke' RETURNING *").bind(ledgeredAt, linkId).first<Record<string, unknown>>(); return row ? mapLink(row) : null; },
    async recordLinkOperationFailure(linkId: string, failureCode: string) { await ready(db); await db.prepare("UPDATE project_share_links SET operation_attempts=operation_attempts+1,last_operation_error=? WHERE id=? AND lifecycle_state IN ('pending-create','pending-revoke')").bind(failureCode, linkId).run(); },
    async preferences(userId: string) { await ready(db); const row = await db.prepare("SELECT * FROM notification_preferences WHERE user_id=?").bind(userId).first<Record<string, unknown>>(); return row ? preferencesFromRow(row) : normalizeNotificationPreferences(); },
    async setPreferences(userId: string, input: unknown, updatedAt: string) { await ready(db); const value = normalizeNotificationPreferences(input as never); await db.prepare("INSERT INTO notification_preferences (user_id,in_app_enabled,email_enabled,event_types_json,updated_at) VALUES (?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET in_app_enabled=excluded.in_app_enabled,email_enabled=excluded.email_enabled,event_types_json=excluded.event_types_json,updated_at=excluded.updated_at").bind(userId, value.inAppEnabled ? 1 : 0, value.emailEnabled ? 1 : 0, JSON.stringify(value.eventTypes), updatedAt).run(); return value; },
    async addNotification(notification: Record<string, unknown>, delivery: { inAppEnabled?: boolean; recipientEmail?: string | null } = {}) { await ready(db); const insertNotification = db.prepare("INSERT INTO notifications (id,organization_id,project_id,user_id,event_type,body_code,subject_refs_json,created_at,read_at,in_app_visible) VALUES (?,?,?,?,?,?,?,?,NULL,?)").bind(notification.id, notification.organizationId, notification.projectId, notification.userId, notification.eventType, notification.bodyCode, JSON.stringify(notification.refs), notification.createdAt, delivery.inAppEnabled === false ? 0 : 1); if (delivery.recipientEmail) await db.batch([insertNotification, db.prepare("INSERT INTO notification_email_outbox (id,notification_id,recipient_email,body_code,subject_refs_json,created_at,attempt_count) VALUES (?,?,?,?,?,?,0)").bind(`email-${notification.id}`, notification.id, delivery.recipientEmail, notification.bodyCode, JSON.stringify(notification.refs), notification.createdAt)]); else await insertNotification.run(); return notification; },
    async listNotifications(userId: string, organizationId: string) { await ready(db); const { results } = await db.prepare("SELECT * FROM notifications WHERE user_id=? AND organization_id=? AND in_app_visible=1 ORDER BY created_at DESC,id DESC LIMIT 100").bind(userId, organizationId).all<Record<string, unknown>>(); return results.map(mapNotification); },
    async markRead(userId: string, organizationId: string, notificationId: string, readAt: string) { await ready(db); await db.prepare("UPDATE notifications SET read_at=? WHERE id=? AND user_id=? AND organization_id=? AND in_app_visible=1").bind(readAt, notificationId, userId, organizationId).run(); },
    async notificationRecipients(organizationId: string, eventType: string, excludeUserId?: string | null) { await ready(db); const { results } = await db.prepare("SELECT u.id,u.email,p.in_app_enabled,p.email_enabled,p.event_types_json FROM organization_memberships m JOIN users u ON u.id=m.user_id LEFT JOIN notification_preferences p ON p.user_id=u.id WHERE m.organization_id=? AND m.status='active' AND u.status='active'").bind(organizationId).all<Record<string, unknown>>(); return results.flatMap((row) => { if (String(row.id) === excludeUserId) return []; let preferences; try { preferences = row.event_types_json == null ? normalizeNotificationPreferences() : preferencesFromRow(row); } catch { return []; } if (!preferences.eventTypes.includes(eventType) || (!preferences.inAppEnabled && !preferences.emailEnabled)) return []; return [{ userId: String(row.id), email: String(row.email), inAppEnabled: preferences.inAppEnabled, emailEnabled: preferences.emailEnabled }]; }); },
    async claimEmailBatch({ organizationId = null, now, leaseExpiresAt, leaseToken, limit = 25 }) { await ready(db); await db.prepare("UPDATE notification_email_outbox SET lease_token=NULL,lease_expires_at=NULL WHERE delivered_at IS NULL AND lease_expires_at IS NOT NULL AND lease_expires_at<=?").bind(now).run(); const where = organizationId ? "AND n.organization_id=?" : ""; const values = organizationId ? [organizationId, limit] : [limit]; const { results } = await db.prepare(`SELECT e.id FROM notification_email_outbox e JOIN notifications n ON n.id=e.notification_id WHERE e.delivered_at IS NULL AND e.lease_token IS NULL ${where} ORDER BY e.created_at,e.id LIMIT ?`).bind(...values).all<{ id: string }>(); const claimed = []; for (const result of results) { const row = await db.prepare("UPDATE notification_email_outbox SET lease_token=?,lease_expires_at=? WHERE id=? AND delivered_at IS NULL AND lease_token IS NULL RETURNING *").bind(leaseToken, leaseExpiresAt, result.id).first<Record<string, unknown>>(); if (row) claimed.push(mapEmail(row)); } return claimed; },
    async markEmailDelivered(id: string, leaseToken: string, deliveredAt: string) { await ready(db); await db.prepare("UPDATE notification_email_outbox SET delivered_at=?,failure_code=NULL,last_attempt_at=?,attempt_count=attempt_count+1,lease_token=NULL,lease_expires_at=NULL WHERE id=? AND lease_token=? AND delivered_at IS NULL").bind(deliveredAt, deliveredAt, id, leaseToken).run(); },
    async markEmailFailed(id: string, leaseToken: string, failureCode: string, attemptedAt: string) { await ready(db); await db.prepare("UPDATE notification_email_outbox SET failure_code=?,last_attempt_at=?,attempt_count=attempt_count+1,lease_token=NULL,lease_expires_at=NULL WHERE id=? AND lease_token=? AND delivered_at IS NULL").bind(failureCode, attemptedAt, id, leaseToken).run(); },
  };
}

export function createMemorySharingRepository({ recipients = [] } = {}) {
  const links = new Map(); const preferences = new Map(); const notifications = []; const emailOutbox = []; const failures = new Map();
  const maybeFail = (name) => { const count = failures.get(name) ?? 0; if (count > 0) { failures.set(name, count - 1); throw new Error(`INJECTED_${name.toUpperCase()}_FAILURE`); } };
  const cloneLink = (link) => structuredClone(link);
  return {
    async createLink(link) { maybeFail("createLink"); const value = { ...cloneLink(link), lifecycleState: "pending-create", creationLedgeredAt: null, revocationLedgeredAt: null, operationAttempts: 0, lastOperationError: null }; links.set(link.id, value); return cloneLink(value); },
    async listLinks(organizationId, projectId) { return [...links.values()].filter((link) => link.organizationId === organizationId && link.projectId === projectId).sort((left, right) => right.createdAt.localeCompare(left.createdAt) || right.id.localeCompare(left.id)).map(cloneLink); },
    async resolveLink(tokenHash, now) { const link = [...links.values()].find((item) => item.tokenHash === tokenHash); return link ? { ...cloneLink(link), status: lifecycleStatus(link, now) } : null; },
    async pendingLinkOperations({ organizationId = null, projectId = null, linkId = null, limit = 100 } = {}) { return [...links.values()].filter((link) => ["pending-create", "pending-revoke"].includes(link.lifecycleState) && (!organizationId || link.organizationId === organizationId) && (!projectId || link.projectId === projectId) && (!linkId || link.id === linkId)).slice(0, limit).map(cloneLink); },
    async markLinkCreated(linkId, ledgeredAt) { maybeFail("markLinkCreated"); const link = links.get(linkId); if (!link || link.lifecycleState !== "pending-create") return null; const value = { ...link, lifecycleState: "active", creationLedgeredAt: ledgeredAt, lastOperationError: null }; links.set(linkId, value); return cloneLink(value); },
    async beginRevoke(organizationId, projectId, linkId, userId, revokedAt) { maybeFail("beginRevoke"); const link = links.get(linkId); if (!link || link.organizationId !== organizationId || link.projectId !== projectId) return null; if (link.lifecycleState !== "active") return { link: cloneLink(link), changed: false }; const value = { ...link, lifecycleState: "pending-revoke", revokedAt, revokedBy: userId, lastOperationError: null }; links.set(linkId, value); return { link: cloneLink(value), changed: true }; },
    async markLinkRevoked(linkId, ledgeredAt) { maybeFail("markLinkRevoked"); const link = links.get(linkId); if (!link || link.lifecycleState !== "pending-revoke") return null; const value = { ...link, lifecycleState: "revoked", revocationLedgeredAt: ledgeredAt, lastOperationError: null }; links.set(linkId, value); return cloneLink(value); },
    async recordLinkOperationFailure(linkId, failureCode) { const link = links.get(linkId); if (link && ["pending-create", "pending-revoke"].includes(link.lifecycleState)) links.set(linkId, { ...link, operationAttempts: link.operationAttempts + 1, lastOperationError: failureCode }); },
    async preferences(userId) { return structuredClone(preferences.get(userId) ?? normalizeNotificationPreferences()); },
    async setPreferences(userId, input) { const value = normalizeNotificationPreferences(input); preferences.set(userId, value); return structuredClone(value); },
    async addNotification(notification, delivery = {}) { const stored = { ...structuredClone(notification), inAppVisible: delivery.inAppEnabled !== false }; notifications.push(stored); if (delivery.recipientEmail) emailOutbox.push({ id: `email-${notification.id}`, notificationId: notification.id, recipientEmail: delivery.recipientEmail, bodyCode: notification.bodyCode, refs: structuredClone(notification.refs), createdAt: notification.createdAt, deliveredAt: null, failureCode: null, attemptCount: 0, lastAttemptAt: null, leaseToken: null, leaseExpiresAt: null }); return structuredClone(notification); },
    async listNotifications(userId, organizationId) { return notifications.filter((item) => item.userId === userId && item.organizationId === organizationId && item.inAppVisible).sort((left, right) => right.createdAt.localeCompare(left.createdAt) || right.id.localeCompare(left.id)).slice(0, 100).map(({ inAppVisible: _hidden, ...item }) => structuredClone(item)); },
    async markRead(userId, organizationId, notificationId, readAt) { const item = notifications.find((entry) => entry.id === notificationId && entry.userId === userId && entry.organizationId === organizationId && entry.inAppVisible); if (item) item.readAt = readAt; },
    async notificationRecipients(organizationId, eventType, excludeUserId = null) { return recipients.flatMap((item) => { if (item.organizationId !== organizationId || item.userId === excludeUserId) return []; const configured = preferences.get(item.userId) ?? normalizeNotificationPreferences({ inAppEnabled: item.inAppEnabled, emailEnabled: item.emailEnabled, eventTypes: item.eventTypes }); if (!configured.eventTypes.includes(eventType) || (!configured.inAppEnabled && !configured.emailEnabled)) return []; return [{ userId: item.userId, email: item.email, inAppEnabled: configured.inAppEnabled, emailEnabled: configured.emailEnabled }]; }).map((item) => structuredClone(item)); },
    async claimEmailBatch({ organizationId = null, now, leaseExpiresAt, leaseToken, limit = 25 }) { for (const item of emailOutbox) if (!item.deliveredAt && item.leaseExpiresAt && item.leaseExpiresAt <= now) { item.leaseToken = null; item.leaseExpiresAt = null; } const claimed = []; for (const item of emailOutbox) { const notification = notifications.find((entry) => entry.id === item.notificationId); if (claimed.length >= limit || item.deliveredAt || item.leaseToken || (organizationId && notification?.organizationId !== organizationId)) continue; item.leaseToken = leaseToken; item.leaseExpiresAt = leaseExpiresAt; claimed.push(structuredClone(item)); } return claimed; },
    async markEmailDelivered(id, leaseToken, deliveredAt) { const item = emailOutbox.find((entry) => entry.id === id && entry.leaseToken === leaseToken && !entry.deliveredAt); if (item) { item.deliveredAt = deliveredAt; item.failureCode = null; item.lastAttemptAt = deliveredAt; item.attemptCount += 1; item.leaseToken = null; item.leaseExpiresAt = null; } },
    async markEmailFailed(id, leaseToken, failureCode, attemptedAt) { const item = emailOutbox.find((entry) => entry.id === id && entry.leaseToken === leaseToken && !entry.deliveredAt); if (item) { item.failureCode = failureCode; item.lastAttemptAt = attemptedAt; item.attemptCount += 1; item.leaseToken = null; item.leaseExpiresAt = null; } },
    _failNext(name, count = 1) { failures.set(name, count); }, _links: links, _notifications: notifications, _emailOutbox: emailOutbox,
  };
}
